# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               CodingGuy
tagline:             ''
description:         '魔都程序猿 cocos2d-x ☑Unity3d<a href="http://weibo.com/541416005" target="_blank">@就叫江南</a>.'
url:                 http://blog.unigamestudio.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              江南
  url:               http://blog.unigamestudio.com
  email:             admin@makegames4fun.com

# Custom vars
version:             1.0.0
